apiVersion: v1
kind: Service
metadata:
  name: progressive-quality-gates-service
  namespace: progressive-quality-gates-staging
  labels:
    app: progressive-quality-gates
spec:
  selector:
    app: progressive-quality-gates
  ports:
  - name: health
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP
